name: Update Earthquake Data

on: 
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Update'
        required: true
        default: 'Update'
        type: choice
        options:
        - Update
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update
        uses: wei/curl@v1
        with:
          args: -X POST ${{secrets.DEPLOY_URL}}
